name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    
    runs-on: ubuntu-latest

    needs: build_test

    steps:
      - uses: actions/checkout@v1
      - name: Create a Release
        uses: actions/create-release@v1
