name: test

on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build container
        run: docker build -t s3s3s .
      - name: import test lib
        run: docker run -i --rm -v `pwd`:/usr/src/app
          -w /usr/src/app
          python:3.8-alpine
          sh -c "apk add build-base libffi-dev && apk add openssl-dev && pip install -t test_libs pytest moto"
      - name: test container
        run: docker run -i --rm -v `pwd`/tests:/usr/src/app/tests
          -v `pwd`/test_libs:/usr/src/test_libs
          -e PYTHONPATH=/usr/src/test_libs
          s3s3s python -m pytest -v -p no:warnings
  
  release:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v1
      - name: Create a Release
        uses: actions/create-release@v1
        if: contains(github.ref, 'tags/v')
